export const INCREMENT = 'INCREMENT';
export const FETCHING_VERBS = 'FETCHING_VERBS';
export const FETCH_VERBS_SUCCESS = 'FETCH_VERBS_SUCCESS';
export const FETCH_VERBS_FAILURE = 'FETCH_VERBS_FAILURE';
export const FETCH_TENSES_FAILURE = 'FETCH_TENSES_FAILURE';
